<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HostelController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and assigned to the "web" middleware group.
| Now create something great!
|
*/

/*
Main function
Route::get('/', function () {
    return view('welcome');
}); */

//Route
//Get or Post
//function(){ echo 'about page';}
//http://127.0.0.1:8000/ 


/*
 @extends('frontend.layout')

@section('content')
    <h1>User_Profile Page</h1>
@endsection 
*/


// Route to the main layout
Route::get('/', function () {
    return view('frontend.layout');
});

// Route for home page
Route::get('/home', function () {
    return view('frontend.home');
});

// Route for about page
Route::get('/about', function () {
    return view('frontend.about');
});

// Route for contact page
Route::get('/contact', function () {
    return view('frontend.contact.blade');
});

// Route for displaying all hostels
Route::get('/hostels', function () {
    return view('frontend.hostels');
});

// Authentication routes
Route::get('/login', function () {
    return view('frontend.auth.login');
});

Route::get('/register', function () {
    return view('frontend.auth.register');
});

// User profile route (example of using middleware)
Route::get('/profile', function () {
    return view('frontend.profile');
})->middleware('auth');

// Route to show a single hostel by ID
Route::get('/hostels/{id}', [HostelController::class, 'show'])->name('hostels.show');

// Authentication routes generated by Auth::routes();
Auth::routes();

// Example route using HomeController
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
